import json
import subprocess
import os
import re
from github import Github, Auth

def run_command_check_output(cmd):
	"""
	BY_AI: Runs a shell command and returns its standard output as bytes.

	Executes the given command string in a shell, suppressing standard error output.
	Raises `subprocess.CalledProcessError` if the command exits with a non-zero status.

	Parameters:
	    cmd (str): The shell command to execute.

	Returns:
	    bytes: The standard output of the command.
	"""
	return subprocess.check_output(cmd, shell=True, stderr=open(os.devnull))

def encode(name, i):
	"""
	BY_AI: Encodes a model name and an integer index into a unique repository slug.

	If the index is greater than zero, appends a hyphen and the index to the name,
	allowing incremental disambiguation of duplicate slugs.

	Parameters:
	    name (str): The base model name / slug.
	    i (int): A non-negative integer suffix index; when 0, no suffix is added.

	Returns:
	    str: The encoded repository slug.
	"""
	result_str = name
	if i > 0:
		result_str += "-"+str(i)
	return result_str


#Dan added the 'Moved Permanently' condition as a bandaid fix for repos that have been deleted
#functionality here may need improvement/rethinking.

def exists(model_id):
	"""
	BY_AI: Checks whether a GitHub repository with the given model identifier already exists.

	Queries the GitHub API for the repository at 'ModelAtlasofTheEarth/<model_id>'.
	Treats 'Not Found' and 'Moved Permanently' responses as non-existent. Any other
	response (including a valid repository object) is treated as existing.

	Parameters:
	    model_id (str): The candidate repository name to look up.

	Returns:
	    bool: True if a repository with that name exists (or is ambiguous), False if it
	        is confirmed not to exist.
	"""
	cmd = "curl https://api.github.com/repos/ModelAtlasofTheEarth/{0}".format(model_id)
	output = json.loads(run_command_check_output(cmd))

	if "message" in output:
		if output["message"] == "Not Found" or output["message"] == 'Moved Permanently':
			return False
		else:
			return True
	else:
		return True

def choice(name):
	"""
	BY_AI: Returns the first available repository slug based on the given base name.

	Iterates through candidate slugs generated by `encode(name, i)` for i = 0, 1, 2, …
	until one is found that does not already correspond to an existing GitHub repository
	under the ModelAtlasofTheEarth organisation.

	Parameters:
	    name (str): The base model name / slug to use as the starting candidate.

	Returns:
	    str: The first available (non-existing) repository slug.
	"""
	i = 0
	while True:
		model_id = encode(name, i)
		if not exists(model_id):
			return model_id
		i += 1


if __name__ == "__main__":
	token = os.environ.get("GITHUB_TOKEN")
	issue_number = int(os.environ.get("ISSUE_NUMBER"))

	# Get issue
	auth = Auth.Token(token)
	g = Github(auth=auth)
	repo = g.get_repo("ModelAtlasofTheEarth/model_submission")
	issue = repo.get_issue(number = issue_number)

	# Parse issue body
	# Identify headings and subsequent text
	regex = r"### *(?P<key>.*?)\s*[\r\n]+(?P<value>[\s\S]*?)(?=###|$)"
	data = dict(re.findall(regex, issue.body))

	slug = data["-> slug"].strip()
	print(choice(slug))
